In [1]:
import pandas as pd

In [2]:
import pandas as pd
data = {
    "Name": ["Jaggu", "Priya", "Amit", "Sneha", "Rahul"],
    "Age": [23, 22, 20, 23, 21],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 60000, 45000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

    Name  Age Department  Salary
0  Jaggu   23         IT   50000
1  Priya   22         HR   60000
2   Amit   20         IT   45000
3  Sneha   23    Finance   70000
4  Rahul   21         HR   55000

In [3]:
df.loc[len(df)] = ["Anjali", 24, "IT", 65000]
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
1   Priya   22         HR   60000
2    Amit   20         IT   45000
3   Sneha   23    Finance   70000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [4]:
df = df.drop(2)
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
1   Priya   22         HR   60000
3   Sneha   23    Finance   70000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [5]:
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
1   Priya   22         HR   60000
3   Sneha   23    Finance   70000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [6]:
print(data)

{'Name': ['Jaggu', 'Priya', 'Amit', 'Sneha', 'Rahul'], 'Age': [23, 22, 20, 23, 21], 'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'], 'Salary': [50000, 60000, 45000, 70000, 55000]}

In [7]:
print(pd.DataFrame(data))

    Name  Age Department  Salary
0  Jaggu   23         IT   50000
1  Priya   22         HR   60000
2   Amit   20         IT   45000
3  Sneha   23    Finance   70000
4  Rahul   21         HR   55000

In [9]:
df = df.drop([1, 3])
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [10]:
df = df.drop("Age", axis=1)
print(df)

     Name Department  Salary
0   Jaggu         IT   50000
4   Rahul         HR   55000
5  Anjali         IT   65000

In [18]:
df = df.rename(columns={"Employee_Name": "EmpName"})
print(df)

  EmpName Department  Salary
0   Jaggu         IT   50000
4   Rahul         HR   55000
5  Anjali         IT   65000

In [22]:
df.sort_values(by="Employee_Salary")

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
4   Rahul         HR            55000
5  Anjali         IT            65000

In [23]:
print(df)

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
4   Rahul         HR            55000
5  Anjali         IT            65000

In [25]:
df.sort_values(by="Employee_Salary", ascending=True)

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
4   Rahul         HR            55000
5  Anjali         IT            65000

In [26]:
df.sort_values(by="Employee_Salary", ascending=False)

  EmpName Department  Employee_Salary
5  Anjali         IT            65000
4   Rahul         HR            55000
0   Jaggu         IT            50000

In [30]:
df.sort_values(
    by=["Department", "Employee_Salary"],
    ascending=[True, False]
)

  EmpName Department  Employee_Salary
4   Rahul         HR            55000
5  Anjali         IT            65000
0   Jaggu         IT            50000

In [31]:
df.sort_values(
    by=["Department", "Employee_Salary"],
    ascending=[True, True]
)

  EmpName Department  Employee_Salary
4   Rahul         HR            55000
0   Jaggu         IT            50000
5  Anjali         IT            65000

In [32]:
df.sort_values(
    by=["Department", "Employee_Salary"],
    ascending=[False, True]
)

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
5  Anjali         IT            65000
4   Rahul         HR            55000

In [33]:
df["EmpName"] = df["EmpName"].str.upper()
print(df)

  EmpName Department  Employee_Salary
0   JAGGU         IT            50000
4   RAHUL         HR            55000
5  ANJALI         IT            65000

In [34]:
df["EmpName"] = df["EmpName"].str.lower()
print(df)

  EmpName Department  Employee_Salary
0   jaggu         IT            50000
4   rahul         HR            55000
5  anjali         IT            65000

In [35]:
df["New_Salary"] = df["Employee_Salary"].apply(lambda x: x + 5000)
print(df)

  EmpName Department  Employee_Salary  New_Salary
0   jaggu         IT            50000       55000
4   rahul         HR            55000       60000
5  anjali         IT            65000       70000

In [36]:
df["Department"] = df["Department"].map({
    "IT": "Information Technology",
    "HR": "Human Resources",
    "Finance": "Finance Department"
})

In [37]:
print(df)

  EmpName              Department  Employee_Salary  New_Salary
0   jaggu  Information Technology            50000       55000
4   rahul         Human Resources            55000       60000
5  anjali  Information Technology            65000       70000

In [42]:
df["Department_Code"] = df["Department"].map({
    "Information Technology": 101,
    "Human Resources": 102,
    "Finance Department": 103
})
print(df)

  EmpName              Department  Employee_Salary  New_Salary  \
0   jaggu  Information Technology            50000       55000
4   rahul         Human Resources            55000       60000
5  anjali  Information Technology            65000       70000

   Department_Code
0              101
4              102
5              101

In [43]:
df["Department"] = df["Department"].replace({
    "IT": "Information Technology",
    "HR": "Human Resources"
})

In [44]:
print(df)

  EmpName              Department  Employee_Salary  New_Salary  \
0   jaggu  Information Technology            50000       55000
4   rahul         Human Resources            55000       60000
5  anjali  Information Technology            65000       70000

   Department_Code
0              101
4              102
5              101

In [45]:
df.describe()

       Employee_Salary    New_Salary  Department_Code
count         3.000000      3.000000         3.000000
mean      56666.666667  61666.666667       101.333333
std        7637.626158   7637.626158         0.577350
min       50000.000000  55000.000000       101.000000
25%       52500.000000  57500.000000       101.000000
50%       55000.000000  60000.000000       101.000000
75%       60000.000000  65000.000000       101.500000
max       65000.000000  70000.000000       102.000000

In [1]:
import pandas as pd

In [2]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Amit", "Sneha", "Rahul"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [55000, 45000, 70000, 65000, 48000],
    "Experience": [2, 5, 4, 6, 3]
}

df = pd.DataFrame(data)

print(df)

   Employee_ID   Name Department  Salary  Experience
0          101   Ravi         IT   55000           2
1          102  Priya         HR   45000           5
2          103   Amit         IT   70000           4
3          104  Sneha    Finance   65000           6
4          105  Rahul         HR   48000           3

In [3]:
high_salary = df[df["Salary"] > 50000]

print(high_salary)

   Employee_ID   Name Department  Salary  Experience
0          101   Ravi         IT   55000           2
2          103   Amit         IT   70000           4
3          104  Sneha    Finance   65000           6

In [4]:
experienced = df[df["Experience"] > 3]

print(experienced)

   Employee_ID   Name Department  Salary  Experience
1          102  Priya         HR   45000           5
2          103   Amit         IT   70000           4
3          104  Sneha    Finance   65000           6

In [5]:
average_salary = df["Salary"].mean()

print("Average Salary:", average_salary)

Average Salary: 56600.0

In [6]:
highest_paid = df[df["Salary"] == df["Salary"].max()]

print(highest_paid)

   Employee_ID  Name Department  Salary  Experience
2          103  Amit         IT   70000           4

In [7]:
import pandas as pd
import numpy as np

sales_data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Product": ["Laptop", "Mobile", "Laptop", "Headphones",
                "Mobile", "Laptop", "Headphones", "Mobile"],
    "Category": ["Electronics", "Electronics", "Electronics", "Accessories",
                 "Electronics", "Electronics", "Accessories", "Electronics"],
    "Quantity": [2, 3, 1, 5, 2, 1, 4, 3],
    "Price": [50000, 20000, 50000, 2000,
              20000, 50000, 2000, 20000],
    "Region": ["North", "South", "North", "East",
               "West", "South", "East", "West"]
}

df_sales = pd.DataFrame(sales_data)

print(df_sales)

   Order_ID     Product     Category  Quantity  Price Region
0      1001      Laptop  Electronics         2  50000  North
1      1002      Mobile  Electronics         3  20000  South
2      1003      Laptop  Electronics         1  50000  North
3      1004  Headphones  Accessories         5   2000   East
4      1005      Mobile  Electronics         2  20000   West
5      1006      Laptop  Electronics         1  50000  South
6      1007  Headphones  Accessories         4   2000   East
7      1008      Mobile  Electronics         3  20000   West

In [8]:
df_sales["Total_Amount"] = df_sales["Quantity"] * df_sales["Price"]

print(df_sales)

   Order_ID     Product     Category  Quantity  Price Region  Total_Amount
0      1001      Laptop  Electronics         2  50000  North        100000
1      1002      Mobile  Electronics         3  20000  South         60000
2      1003      Laptop  Electronics         1  50000  North         50000
3      1004  Headphones  Accessories         5   2000   East         10000
4      1005      Mobile  Electronics         2  20000   West         40000
5      1006      Laptop  Electronics         1  50000  South         50000
6      1007  Headphones  Accessories         4   2000   East          8000
7      1008      Mobile  Electronics         3  20000   West         60000

In [9]:
total_revenue = df_sales["Total_Amount"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 378000

In [10]:
best_selling = df_sales.groupby("Product")["Quantity"].sum()

print(best_selling)

Product
Headphones    9
Laptop        4
Mobile        8
Name: Quantity, dtype: int64

In [11]:
best_product = best_selling.idxmax()

print("Best Selling Product:", best_product)

Best Selling Product: Headphones

In [12]:
print("Quantity Sold:", best_selling.max())

Quantity Sold: 9

In [13]:
category_revenue = df_sales.groupby("Category")["Total_Amount"].sum()

print(category_revenue)

Category
Accessories     18000
Electronics    360000
Name: Total_Amount, dtype: int64

In [14]:
highest_category = category_revenue.idxmax()

print("Highest Revenue Category:", highest_category)

Highest Revenue Category: Electronics

In [15]:
region_sales = df_sales.groupby("Region")["Total_Amount"].sum()

print(region_sales)

Region
East      18000
North    150000
South    110000
West     100000
Name: Total_Amount, dtype: int64

In [16]:
top_region = region_sales.idxmax()

print("Region with Highest Sales:", top_region)

Region with Highest Sales: North

In [17]:
top_5_orders = df_sales.sort_values(
    by="Total_Amount",
    ascending=False
).head(5)

print(top_5_orders)

   Order_ID Product     Category  Quantity  Price Region  Total_Amount
0      1001  Laptop  Electronics         2  50000  North        100000
1      1002  Mobile  Electronics         3  20000  South         60000
7      1008  Mobile  Electronics         3  20000   West         60000
2      1003  Laptop  Electronics         1  50000  North         50000
5      1006  Laptop  Electronics         1  50000  South         50000

In [18]:
print(df_sales.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [19]:
print("Duplicate Records:", df_sales.duplicated().sum())

Duplicate Records: 0

In [20]:
df_sales = df_sales.drop_duplicates()

print(df_sales)

   Order_ID     Product     Category  Quantity  Price Region  Total_Amount
0      1001      Laptop  Electronics         2  50000  North        100000
1      1002      Mobile  Electronics         3  20000  South         60000
2      1003      Laptop  Electronics         1  50000  North         50000
3      1004  Headphones  Accessories         5   2000   East         10000
4      1005      Mobile  Electronics         2  20000   West         40000
5      1006      Laptop  Electronics         1  50000  South         50000
6      1007  Headphones  Accessories         4   2000   East          8000
7      1008      Mobile  Electronics         3  20000   West         60000

In [21]:
print(df_sales.isnull().sum())

Order_ID        0
Product         0
Category        0
Quantity        0
Price           0
Region          0
Total_Amount    0
dtype: int64

In [22]:
df_sales["Quantity"] = df_sales["Quantity"].fillna(
    df_sales["Quantity"].mean()
)

df_sales["Price"] = df_sales["Price"].fillna(
    df_sales["Price"].mean()
)

In [23]:
df_sales["Product"] = df_sales["Product"].fillna("Unknown")

df_sales["Category"] = df_sales["Category"].fillna("Unknown")

df_sales["Region"] = df_sales["Region"].fillna("Unknown")

In [24]:
df_sales["Total_Amount"] = (
    df_sales["Quantity"] * df_sales["Price"]
)

In [25]:
df_sales.to_csv("cleaned_sales.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!