In [1]:
import pandas as pd

In [2]:
import pandas as pd
data = {
    "Name": ["Jaggu", "Priya", "Amit", "Sneha", "Rahul"],
    "Age": [23, 22, 20, 23, 21],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 60000, 45000, 70000, 55000]
}
df = pd.DataFrame(data)
print(df)

    Name  Age Department  Salary
0  Jaggu   23         IT   50000
1  Priya   22         HR   60000
2   Amit   20         IT   45000
3  Sneha   23    Finance   70000
4  Rahul   21         HR   55000

In [3]:
df.loc[len(df)] = ["Anjali", 24, "IT", 65000]
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
1   Priya   22         HR   60000
2    Amit   20         IT   45000
3   Sneha   23    Finance   70000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [4]:
df = df.drop(2)
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
1   Priya   22         HR   60000
3   Sneha   23    Finance   70000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [5]:
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
1   Priya   22         HR   60000
3   Sneha   23    Finance   70000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [6]:
print(data)

{'Name': ['Jaggu', 'Priya', 'Amit', 'Sneha', 'Rahul'], 'Age': [23, 22, 20, 23, 21], 'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'], 'Salary': [50000, 60000, 45000, 70000, 55000]}

In [7]:
print(pd.DataFrame(data))

    Name  Age Department  Salary
0  Jaggu   23         IT   50000
1  Priya   22         HR   60000
2   Amit   20         IT   45000
3  Sneha   23    Finance   70000
4  Rahul   21         HR   55000

In [9]:
df = df.drop([1, 3])
print(df)

     Name  Age Department  Salary
0   Jaggu   23         IT   50000
4   Rahul   21         HR   55000
5  Anjali   24         IT   65000

In [10]:
df = df.drop("Age", axis=1)
print(df)

     Name Department  Salary
0   Jaggu         IT   50000
4   Rahul         HR   55000
5  Anjali         IT   65000

In [18]:
df = df.rename(columns={"Employee_Name": "EmpName"})
print(df)

  EmpName Department  Salary
0   Jaggu         IT   50000
4   Rahul         HR   55000
5  Anjali         IT   65000

In [22]:
df.sort_values(by="Employee_Salary")

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
4   Rahul         HR            55000
5  Anjali         IT            65000

In [23]:
print(df)

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
4   Rahul         HR            55000
5  Anjali         IT            65000

In [25]:
df.sort_values(by="Employee_Salary", ascending=True)

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
4   Rahul         HR            55000
5  Anjali         IT            65000

In [26]:
df.sort_values(by="Employee_Salary", ascending=False)

  EmpName Department  Employee_Salary
5  Anjali         IT            65000
4   Rahul         HR            55000
0   Jaggu         IT            50000

In [30]:
df.sort_values(
    by=["Department", "Employee_Salary"],
    ascending=[True, False]
)

  EmpName Department  Employee_Salary
4   Rahul         HR            55000
5  Anjali         IT            65000
0   Jaggu         IT            50000

In [31]:
df.sort_values(
    by=["Department", "Employee_Salary"],
    ascending=[True, True]
)

  EmpName Department  Employee_Salary
4   Rahul         HR            55000
0   Jaggu         IT            50000
5  Anjali         IT            65000

In [32]:
df.sort_values(
    by=["Department", "Employee_Salary"],
    ascending=[False, True]
)

  EmpName Department  Employee_Salary
0   Jaggu         IT            50000
5  Anjali         IT            65000
4   Rahul         HR            55000

In [33]:
df["EmpName"] = df["EmpName"].str.upper()
print(df)

  EmpName Department  Employee_Salary
0   JAGGU         IT            50000
4   RAHUL         HR            55000
5  ANJALI         IT            65000

In [34]:
df["EmpName"] = df["EmpName"].str.lower()
print(df)

  EmpName Department  Employee_Salary
0   jaggu         IT            50000
4   rahul         HR            55000
5  anjali         IT            65000

In [35]:
df["New_Salary"] = df["Employee_Salary"].apply(lambda x: x + 5000)
print(df)

  EmpName Department  Employee_Salary  New_Salary
0   jaggu         IT            50000       55000
4   rahul         HR            55000       60000
5  anjali         IT            65000       70000

In [36]:
df["Department"] = df["Department"].map({
    "IT": "Information Technology",
    "HR": "Human Resources",
    "Finance": "Finance Department"
})

In [37]:
print(df)

  EmpName              Department  Employee_Salary  New_Salary
0   jaggu  Information Technology            50000       55000
4   rahul         Human Resources            55000       60000
5  anjali  Information Technology            65000       70000

In [42]:
df["Department_Code"] = df["Department"].map({
    "Information Technology": 101,
    "Human Resources": 102,
    "Finance Department": 103
})
print(df)

  EmpName              Department  Employee_Salary  New_Salary  \
0   jaggu  Information Technology            50000       55000
4   rahul         Human Resources            55000       60000
5  anjali  Information Technology            65000       70000

   Department_Code
0              101
4              102
5              101

In [43]:
df["Department"] = df["Department"].replace({
    "IT": "Information Technology",
    "HR": "Human Resources"
})

In [44]:
print(df)

  EmpName              Department  Employee_Salary  New_Salary  \
0   jaggu  Information Technology            50000       55000
4   rahul         Human Resources            55000       60000
5  anjali  Information Technology            65000       70000

   Department_Code
0              101
4              102
5              101

In [45]:
df.describe()

       Employee_Salary    New_Salary  Department_Code
count         3.000000      3.000000         3.000000
mean      56666.666667  61666.666667       101.333333
std        7637.626158   7637.626158         0.577350
min       50000.000000  55000.000000       101.000000
25%       52500.000000  57500.000000       101.000000
50%       55000.000000  60000.000000       101.000000
75%       60000.000000  65000.000000       101.500000
max       65000.000000  70000.000000       102.000000